// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var OffsetguessTest = newAsset("offsetguess-test.c", "1bf02e4a0991e78c4f06de9841ea64bb9cc67fcb768953d143e700c3ee114d71")
