// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var OffsetguessTest = newAsset("offsetguess-test.c", "6f3c617167d7fa2938c2d35fb45eeb61a6f2f28abe6b00cf68820e96e7594a42")
